## ThreatMap — Algorithm to generate an Influence Map.
## Evaluates the danger level of every tile on the board based on enemy positioning.

class_name ThreatMap

static func generate(state: BattleState, team: int) -> Dictionary:
	## Generates a Dictionary mapping Vector2i -> threat score (int).
	## Threat is generated by all alive enemies of the specified team.
	## A score of 0 means perfectly safe (outside all enemy move+attack ranges).
	var map: Dictionary = {}
	
	# Default all walkable board tiles to 0 threat
	for x in range(state.boardSize.x):
		for y in range(state.boardSize.y):
			var p = Vector2i(x, y)
			if state.isWalkable(p):
				map[p] = 0
				
	# Loop all enemies to apply threat
	for enemyID in state.getAliveMonsterIDs():
		var enemy = state.getMonster(enemyID)
		if enemy.team == team:
			continue
			
		# Simplified threat evaluation: Move range + Max Attack Range
		# We use Manhattan distance spread to keep it blazing fast without full pathfinding
		var maxRange = 1 # Fallback melee range
		for spellSet in enemy.spellSets:
			for spell in spellSet:
				if not spell.heals and spell.range > maxRange:
					maxRange = spell.range
					
		var totalDangerZone = enemy.move + maxRange
		var enemyPos = state.getMonsterPosition(enemyID)
		
		# Apply threat score (using ATK stat as weight) to all tiles within the danger zone
		for x in range(-totalDangerZone, totalDangerZone + 1):
			for y in range(-totalDangerZone, totalDangerZone + 1):
				if abs(x) + abs(y) <= totalDangerZone:
					var p = enemyPos + Vector2i(x, y)
					if map.has(p):
						map[p] += enemy.atk
						
	return map
